parameters:
    ev_ip_field.form.class: Ev\IpFieldTypeBundle\Type\IpType

services:
    ev.ipfield.form.type:
        class: %ev_ip_field.form.class%
        tags:
            - { name: form.type, alias: ipfield }