parameters:
    evotodi_ip_field.form.class: Evotodi\IpFieldTypeBundle\Type\IpType

services:
    evotodi.ipfield.form.type:
        class: %evotodi_ip_field.form.class%
        tags:
            - { name: form.type, alias: ipfield }